name: Demande de fonctionnalité
description: Proposer une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
      placeholder: Décrivez le besoin ou la limitation actuelle.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      placeholder: Décrivez la fonctionnalité souhaitée.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      placeholder: Autres approches considérées.
